name: flutter_login_facebook
description: Login via Facebook. Easily add Facebook login feature in your application. User profile information included.
version: 0.1.2+3
homepage: https://github.com/Innim/flutter_login_facebook
repository: https://github.com/Innim/flutter_login_facebook
issue_tracker: https://github.com/Innim/flutter_login_facebook/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_login_facebook
        pluginClass: FlutterLoginFacebookPlugin
      ios:
        pluginClass: FlutterLoginFacebookPlugin
