name: flutter_login_facebook
description: Login via Facebook. Easily add Facebook login feature in your application. User profile information included.
version: 1.0.0-nullsafety.1
homepage: https://github.com/Innim/flutter_login_facebook
repository: https://github.com/Innim/flutter_login_facebook
issue_tracker: https://github.com/Innim/flutter_login_facebook/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.25.0-0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^1.0.1-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  innim_lint: ^0.1.7

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_login_facebook
        pluginClass: FlutterLoginFacebookPlugin
      ios:
        pluginClass: FlutterLoginFacebookPlugin
